name: Continuous Integration

on:
  push:
    branches: [ 'main', 'develop' ]
  pull_request:
    branches: [ 'main', 'develop' ]

jobs:

  #####################
  # Lint the Codebase #
  #####################

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        uses: psf/black@stable

  #####################
  # Test the Codebase #
  #####################

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency manager
        run: make install-dependency-manager
      - name: Install dependencies
        run: make install-dependencies
      - name: Run test suite
        run: |
          python -c "import ontime"
          python -c "import src.ontime"
          make test

  #####################
  # Build the Package #
  #####################

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependency manager
        run: make install-dependency-manager
      - name: Install dependencies
        run: make install-dependencies
      - name: Build package
        run: make build
